#!/bin/sh
USER=root
HOST=49.12.104.79
DIR=var/www/soliprem   # the directory where your web site files should go
 
hugo && rsync -avz --delete public/ ${USER}@${HOST}:/${DIR} # this will delete everything on the server that's not in the local public folder 
 
exit 0
